// <auto-generated />
namespace SimpleBillingApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Changes1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changes1));
        
        string IMigrationMetadata.Id
        {
            get { return "201510141247481_Changes1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
